# -*- coding: utf-8 -*-
"""HW5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhEmWWYqUTcjjmQGbze96f8kvITim8Ps
"""

import numpy as np

def getBondPrice(y, face, couponRate, m, ppy=1):
  ccf=couponRate*face/ppy
  times=np.arange(1,m+1)
  pvf=np.power(1+y, times)
  pvcf=ccf/pvf
  pvface=face/pvf[-1]
  BondPrice=pvface+pvcf.sum()
  return BondPrice

print(getBondPrice(0.03, 2000000,0.04,10))

def getBondDuration(y, face, couponRate, m, ppy=1):
  ccf=couponRate*face/ppy
  times=np.arange(1,m+1)
  pvf=np.power(1+y, times)
  pvcf=ccf/pvf
  pvface=face/pvf[-1]
  BondPrice=pvface+pvcf.sum()
  d1=pvcf*times
  d2=pvface*m
  Duration=(np.sum(d1)+d2)/BondPrice
  return Duration

print(getBondDuration(0.03, 2000000,0.04,10))

def FizzBuzz(start, finish):
  numvec=np.arange(start, finish+1)
  condition=[(numvec % 15 == 0), (numvec % 3 == 0), (numvec % 5 == 0)]
  choice=['FizzBuzz', 'Fizz', 'Buzz']
  return np.select(condition, choice, default=numvec.astype(str))

FizzBuzz(16,30)







































